# Copyright 2017 <chaishushan{AT}gmail.com>. All rights reserved.
# Use of this source code is governed by a Apache
# license that can be found in the LICENSE file.

default:
	@gcc -o a.out _testmain.c
	@./a.out
	-@rm a.out

clean:
	-rm a.out
